camera:
  resolution:
    width: 1920
    height: 1130
  recordings_folder: "recordings"
  chunk_size_seconds: 10
  max_chunks: 10
server:
  host: "0.0.0.0"
  port: 8443
  rate_limiting:
    default:
      per_day: 500
      per_hour: 50
